<<<<<<< HEAD
# Generated by Django 5.2 on 2025-05-04 07:08
=======
# Generated by Django 5.2 on 2025-05-03 15:16
>>>>>>> db895a93631b250cb8e265dead1175fe51df9a09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attribute', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
