
# Generated by Django 5.2 on 2025-05-04 07:08

# Generated by Django 5.2 on 2025-05-03 15:16


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('add_region_at', models.DateTimeField(auto_now_add=True)),
                ('parent_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subregions', to='region.region')),
            ],
        ),
    ]
