<<<<<<< HEAD
# Generated by Django 5.2 on 2025-05-04 07:08
=======
# Generated by Django 5.2 on 2025-05-03 15:16
>>>>>>> db895a93631b250cb8e265dead1175fe51df9a09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(default=0)),
                ('payment_at', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[(1, 'Online Transaction'), (2, 'ATM')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('status', models.SmallIntegerField(choices=[(1, 'Pending'), (2, 'Processing'), (3, 'Completed'), (4, 'Canceled')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
