# Generated by Django 5.2 on 2025-05-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('1', 'Online Transaction'), ('2', 'ATM')], default=1),
        ),
    ]
