# Generated by Django 5.2 on 2025-05-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotedproduct',
            name='promo_type',
            field=models.SmallIntegerField(choices=[(1, 'Basic'), (2, 'Popular'), (3, 'Special')]),
        ),
    ]
