<<<<<<< HEAD
# Generated by Django 5.2 on 2025-05-04 07:08
=======
# Generated by Django 5.2 on 2025-05-03 15:16
>>>>>>> db895a93631b250cb8e265dead1175fe51df9a09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_price', models.BigIntegerField()),
                ('status', models.SmallIntegerField(choices=[(1, '')], default=1)),
                ('payment_method', models.CharField(choices=[(1, 'Bozor24 account'), (2, 'Pay in received')])),
                ('customer_address', models.TextField(choices=[(1, '')])),
                ('is_paid', models.BooleanField(default=False)),
                ('is_released', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price_at_purchase', models.BigIntegerField()),
            ],
        ),
    ]
